quantity = int(input("จำนวนปืนที่รับมาขาย: "))
cost_price = int(input("ต้นทุนของปืนที่รับมา: "))
sell_price = int(input("ราคาที่นำไปขายต่อ: "))
team_member = int(input("จำนวนลูกน้องไปทำงาน: "))

print("ต้นทุนทั้งหมด:" , quantity * cost_price)
print("ราคาขายทั้งหมด:", quantity * sell_price)
print("กำไรสุทธิ:", (quantity * sell_price) - (quantity * cost_price))
print("ส่วนแบ่งให้บอส:", (quantity * sell_price) * (20/100))
print("เงินที่แต่ละคนได้:", ((quantity * sell_price) - ((quantity * sell_price) * (20/100))) /team_member)
